### ISSUE TITLE
An if-block bug that is similar to Apple’s SSL "goto fail" bug

### ISSUE THREAD

**Issue by johnjohnlin** [yodalee/NixieClock#1]
Hello, it seems that there should be a pair of brace here.
https://github.com/yodalee/NixieClock/blob/master/software/DS1309/DS1309.ino#L40

```cpp
  if(timeStatus() != timeSet) // Here
    digitalWrite(LED, HIGH);
    delay(100);
    digitalWrite(LED, LOW);
```

**Comment by yodalee** [comment]
Fixed.
Though the brace actually not affect the function :)
